name       : isync
version    : 1.4.2
release    : 3
source     :
    - https://sourceforge.net/projects/isync/files/isync/1.4.2/isync-1.4.2.tar.gz/download : 1935e7ed412fd6b5928aaea656f290aa8d3222c5feda31534903934ce4755343
license    : GPL-2.0-or-later
component  : network.mail
summary    : isync is a command line application which synchronizes mailboxes
description: |
    isync is a command line application which synchronizes mailboxes; currently Maildir and IMAP4 mailboxes are supported. New messages, message deletions and flag changes can be propagated both ways. isync is suitable for use in IMAP-disconnected mode.
builddeps  :
    - pkgconfig(libsasl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
