name       : isync
version    : 1.3.1
release    : 2
source     :
    - https://iweb.dl.sourceforge.net/project/isync/isync/1.3.1/isync-1.3.1.tar.gz : 68cb4643d58152097f01c9b3abead7d7d4c9563183d72f3c2a31d22bc168f0ea
license    : GPL-2.0-or-later
component  : network.mail
summary    : isync is a command line application which synchronizes mailboxes
description: |
    isync is a command line application which synchronizes mailboxes; currently Maildir and IMAP4 mailboxes are supported. New messages, message deletions and flag changes can be propagated both ways. isync is suitable for use in IMAP-disconnected mode.
builddeps  :
    - pkgconfig(libsasl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
