name       : isync
version    : 1.3.0
release    : 1
source     :
    - https://sourceforge.net/projects/isync/files/isync/1.3.0/isync-1.3.0.tar.gz : 8d5f583976e3119705bdba27fa4fc962e807ff5996f24f354957178ffa697c9c
license    : GPL-2.0
component  : network.mail
summary    : isync is a command line application which synchronizes mailboxes
description: |
    isync is a command line application which synchronizes mailboxes; currently Maildir and IMAP4 mailboxes are supported. New messages, message deletions and flag changes can be propagated both ways. isync is suitable for use in IMAP-disconnected mode.
    Synchronization is based on unique message identifiers (UIDs), so no identification conflicts can occur (as opposed to some other mail synchronizers).
    Synchronization state is kept in one local text file per mailbox pair; multiple replicas of a mailbox can be maintained.
builddeps  :
    - pkgconfig(libsasl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
